pull_request_rules:
  - name: Random Request Review PRs
    conditions:
      - "#review-requested=0"
    actions:
      request_review:
        users:
          - jackcenter
          - livanov93
        random_count: 1

  - name: Backport to galactic at reviewers discretion
    conditions:
      - base=main
      - "label=backport-galactic"
    actions:
      backport:
        branches:
          - galactic

  - name: Backport to foxy at reviewers discretion
    conditions:
      - base=main
      - "label=backport-foxy"
    actions:
      backport:
        branches:
          - foxy

  - name: Ask to resolve conflict
    conditions:
      - conflict
      - author!=mergify
    actions:
        comment:
          message: This pull request is in conflict. Could you fix it @{{author}}?
