pull_request_rules:
  - name: Backport to galactic at reviewers discretion
    conditions:
      - base=master
      - "label=backport-galactic"
    actions:
      backport:
        branches:
          - galactic

  - name: Backport to jazzy at reviewers discretion
    conditions:
      - base=master
      - "label=backport-jazzy"
    actions:
      backport:
        branches:
          - jazzy

  - name: Backport to kilted at reviewers discretion
    conditions:
      - base=master
      - "label=backport-kilted"
    actions:
      backport:
        branches:
          - kilted

  - name: Ask to resolve conflict
    conditions:
      - conflict
      - author!=mergify
    actions:
        comment:
          message: This pull request is in conflict. Could you fix it @{{author}}?
