# The ConfigureStartController service allows you to configure and start a single controller
# inside controller_manager

# To configure and start a controller, specify the "name" of the controller.
# The return value "ok" indicates if the controller was successfully
# configured and started or not.

string name
---
bool ok
