# The ListHardwareComponents service returns a list of hardware HardwareComponentsState.
# This will convey name, component_type, state and type of the components
# that are loaded inside the resource_manager.

---
HardwareComponentState[] component
