# The LoadStartController service allows you to load, configure and start a single controller
# inside controller_manager

# To load, configure and start a controller, specify the "name" of the controller.
# The return value "ok" indicates if the controller was successfully
# constructed, configured and started or not.

string name
---
bool ok
