# The LoadController service allows you to load a single controller
# inside controller_manager

# To load a controller, specify the "name" of the controller.
# The return value "ok" indicates if the controller was successfully
# constructed and initialized or not.

string name
---
bool ok
