# The LoadConfigureController service allows you to load and configure a single controller
# inside controller_manager

# To load and configure a controller, specify the "name" of the controller.
# The return value "ok" indicates if the controller was successfully
# constructed and configured or not.

string name
---
bool ok
