# The UnloadController service allows you to unload a single controller
# from controller_manager

# To unload a controller, specify the "name" of the controller.
# The return value "ok" indicates if the controller was successfully
# unloaded or not

string name
---
bool ok
