# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install clang-format-10
      run: sudo apt-get install clang-format-10 cppcheck
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files --hook-stage manual
