name: Foxy Binary Build - main
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
<<<<<<< HEAD:.github/workflows/foxy-binary-build-main.yml
    branches:
      - foxy
=======
>>>>>>> b8c5418 (remove workflow dispatch branch (#1362)):.github/workflows/iron-binary-build-main.yml
  pull_request:
    branches:
      - foxy
  push:
    branches:
      - foxy
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: foxy
      ros_repo: main
      upstream_workspace: ros2_control-not-released.foxy.repos
      ref_for_scheduled_build: foxy
