name: Galactic Semi-Binary Build - main
# description: 'Build & test that compiles the main dependencies from source.'

on:
  workflow_dispatch:
<<<<<<< HEAD:.github/workflows/galactic-semi-binary-build-main.yml
    branches:
      - galactic
=======
  pull_request:
    branches:
      - iron
>>>>>>> b8c5418 (remove workflow dispatch branch (#1362)):.github/workflows/iron-semi-binary-build-testing.yml
  push:
    branches:
      - galactic
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

jobs:
  semi_binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: galactic
      ros_repo: main
      upstream_workspace: ros2_control.galactic.repos
      ref_for_scheduled_build: galactic
