name: Humble Binary Build - testing
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
    branches:
      - humble
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: humble
      ros_repo: testing
      upstream_workspace: ros2_control-not-released.humble.repos
      ref_for_scheduled_build: humble
