name: Iron Check Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - iron
    paths:
      - '**.rst'
      - '**.md'
      - '**.yaml'

jobs:
  check-docs:
    name: Check Docs
    uses: ros-controls/control.ros.org/.github/workflows/reusable-sphinx-check-single-version.yml@iron
    with:
      ROS2_CONTROL_PR: ${{ github.ref }}
