name: Coverage Build - Iron
on:
  workflow_dispatch:
  push:
    branches:
      - iron
  pull_request:
    branches:
      - iron

jobs:
  coverage_iron:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: iron
      os_name: ubuntu-22.04
