name: Kilted Semi-Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all ros2_control dependencies from source.'

on:
  workflow_dispatch:
  pull_request: &event
    branches:
      - kilted
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/kilted-semi-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_control.kilted.repos'
  push: *event
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  semi-binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: kilted
      ros_repo: testing
      upstream_workspace: ros2_control.kilted.repos
      ref_for_scheduled_build: kilted
  semi-binary-clang:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: kilted
      ros_repo: testing
      upstream_workspace: ros2_control.kilted.repos
      ref_for_scheduled_build: kilted
      additional_debs: clang
      c_compiler: clang
      cxx_compiler: clang++
      not_test_build: true
