# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  push:

jobs:
  default:

    env:
      ROS_DISTRO: rolling
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work

    name: "rolling"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master
