# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  push:

jobs:
  default:

    env:
      ROS_DISTRO: humble

    name: ${{ github.env.ROS_DISTRO }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: industrial_ci
        env:
          PRERELEASE: true
          BASEDIR: ${{ github.workspace }}/.work
          DOCKER_IMAGE: ghcr.io/ros-controls/ros:${{ env.ROS_DISTRO }}-ubuntu-testing
        uses: ros-industrial/industrial_ci@master
