name: Reviewer lottery
# pull_request_target takes the same events as pull_request,
# but it runs on the base branch instead of the head branch.
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  assign_reviewers:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-reviewer-lottery.yml@master
