name: Check Rolling Compatibility on Jazzy
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>
# description: 'Build & test the rolling version on Jazzy distro.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '.github/workflows/rolling-compatibility-jazzy-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_control.rolling.repos'
  push:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '.github/workflows/rolling-compatibility-jazzy-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_control.rolling.repos'

jobs:
  build-on-jazzy:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy]
        ROS_REPO: [testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: ros2_control.rolling.repos
      ref_for_scheduled_build: master
