name: Rolling Semi-Binary Build - main
# description: 'Build & test that compiles the main dependencies from source.'

on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

jobs:
  semi_binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: rolling
      ros_repo: main
      upstream_workspace: ros2_control.rolling.repos
      ref_for_scheduled_build: master
