name: ABI Compatibility Check
on:
  pull_request:
    branches:
      - master

jobs:
  abi_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: rolling
          ROS_REPO: main
          ABICHECK_URL: github:${{ github.repository }}#${{ github.base_ref }}
          NOT_TEST_BUILD: true
          OS_CODE_NAME: focal
          BEFORE_INSTALL_UPSTREAM_DEPENDENCIES: |
            export ROSDISTRO_INDEX_URL=https://raw.githubusercontent.com/ros/rosdistro/rolling/2022-01-28/index-v4.yaml
            rosdep update
