name: Build & Test ros2_control with source-based setup
on:
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  ci_source:
    name: Galactic source job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          # build all packages listed in the meta package
          package-name:
            controller_interface
            controller_manager
            controller_manager_msgs
            hardware_interface
            ros2controlcli
            ros2_control
            ros2_control_test_assets
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/ros2_control/ros2_control.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@v1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
